services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py seed_exercises &&
             python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/app
      - db_data:/app/data/
      - static_volume:/app/staticfiles

    ports:
      - "8000:8000"

volumes:
  db_data:
  static_volume: