# Generated by Django 5.2.6 on 2025-10-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='goal',
            field=models.TextField(blank=True, help_text="e.g., 'Build Strength', 'Weight Loss'", null=True),
        ),
    ]
